<style>
    .line-hight{
        line-height: 3;
    }
    </style>
    @php
        $question = [
            'q1' => "With advanced technology, ",
            'q2' => "from one continent to another is relatively easy nowadays and the number of foreign",
            'q3' => "is increasing. Although revenue from tourism is a much needed resource, overseas tourists are not always welcome in the countries they visit. This essay will outline the",
            'q4' => "of tourism and will outline some of the reasons why overseas tourists are not always welcome. There are a number of reasons why",
            'q5' => "is regarded in a positive light. First of all, the income generated by overseas visitors is substantial. In a country such as Thailand, for",
            'q6' => ", foreign income from tourism is essential in helping to develop the nation. It provides a living for hundreds of thousands of people: the hotel, transport and retail sectors all benefit from overseas visitors.",
            'q7' => "from the financial aspect, foreign visitors also provide a fresh perspective for the local people. Aspects such as foreign languages, culture and traditions can help ",
            'q8' => "the minds of local people. Ironically, these foreign cultural values may also have a",
            'q9' => "impact on local communities. The erosion of local traditions can result from the introduction of outside cultures. For example, popular ",
            'q10' => "and Hollywood movies from the USA can undermine the Thai traditional culture. This ‘cultural pollution’ is also accompanied by ",
            'q11' => "pollution, as more and more resorts are built to provide accommodation for the overseas tourists. All in all, then,",
            'q12' => "foreign tourists can help sustain and expand a nation’s economy, people should also be aware that cultural and environmental pollution can have a negative",
        ];
    
        $endQuestion = "on the tourist destinations.";
    
        $choice = [
            'c1' => "advantages",    
            'c2' => "Apart",  
            'c3' => "environmental",     
            'c4' => "example", 
            'c5' => "expand",     
            'c6' => "impact",   
            'c7' => "music",   
            'c8' => "negative",     
            'c9' => "tourism",     
            'c10' => "tourists",      
            'c11' => "travelling",      
            'c12' => "while",      
        ];
       
    @endphp
    <div class="row">
        <div class="col-xl-12 col-md-12">
            <div class="card-box text-dark font-16">
                <p class="lead">
                    {{$pageTitle['topic']}}
                </p>
                <div class="mb-2">
                    @for ($i = 1; $i <= count($question); $i++)
                        <div class="line-hight d-inline w-auto mb-2 ">
                            {{ $question['q'.$i] }}
                        </div>
                        <select class="form-control d-inline w-auto mx-2 mb-2 ">
                            <option value="">-Select-</option>
                            @foreach ($choice as $choices)
                                <option value="{{ $choices }}">{{ $choices }}</option>
                            @endforeach
                        </select>
                    @endfor
                    {{ $endQuestion }}
                </div>
            </div>
        </div>
    </div>
    
    @section('button-control')
        <button id="check-answer" class="btn btn-info">Check Answers</button>
    @endsection
    
    @section('js')
        <script>
            const answers = [
                "travelling", //1
                "tourists",//2
                "advantages",//3
                "tourism",//4
                "example",//5
                "Apart",//6
                "expand",//7
                "negative",//8
                "music",//9
                "environmental",//10
                "while",//11
                "impact",//12
            ]
            
    
            let score = 0
    
            $("#show-answer").hide(true)
    
            $('#check-answer').on('click', function() {
                
                $('select').each((idx, item) => {
                    if($(item).val().trim() == answers[idx].trim()) {
                        $(item).addClass('border border-success')
                        $('<i class="fas fa-check text-success mr-2"></i>').insertAfter($(item))
                        score++
                    } else {
                        $(item).addClass('border border-danger')
                        $(`<i class="fas fa-times text-danger mr-2"></i><span class="text-success mr-2">${Array.isArray(answers[idx]) ? answers[idx][1] : answers[idx]}</span>`).insertAfter($(item))
                    }
                })
    
                if(score == answers.length){
                    alert("you're awesome")
                }else{
                    alert('Your score is ' + score + '/' + answers.length)
                }
    
                $("#check-answer").prop('disabled','true')
            })
        </script>
    @stop